/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatPopup: typeof import('./src/components/ChatPopup/index.vue')['default']
    ChatToolbar: typeof import('./src/components/ChatToolbar/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmojiBox: typeof import('./src/components/EmojiBox.vue')['default']
    MessageBox: typeof import('./src/components/messageBox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolbarChooseMusic: typeof import('./src/components/ChatToolbar/components/ToolbarChooseMusic.vue')['default']
    ToolbarCollect: typeof import('./src/components/ChatToolbar/components/ToolbarCollect.vue')['default']
    ToolbarEmotion: typeof import('./src/components/ChatToolbar/components/ToolbarEmotion.vue')['default']
    ToolbarQueueMusic: typeof import('./src/components/ChatToolbar/components/ToolbarQueueMusic.vue')['default']
    UserBox: typeof import('./src/components/userBox.vue')['default']
    WxPre: typeof import('./src/components/ChatToolbar/components/WxPre.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
